# Generated by Django 3.1.14 on 2022-04-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220424_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='main_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments', to='articles.comment', verbose_name='Основной комментарий'),
        ),
    ]
