# Generated by Django 3.1.14 on 2022-04-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nested_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности комментария'),
        ),
    ]
