# Generated by Django 3.1.14 on 2022-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220419_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NestingComment',
            new_name='NestedComment',
        ),
        migrations.AddConstraint(
            model_name='nestedcomment',
            constraint=models.UniqueConstraint(fields=('main_comment', 'nested_comment'), name='unique_nested_comment'),
        ),
    ]
