# Generated by Django 3.1.14 on 2022-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220419_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_comment',
            field=models.PositiveIntegerField(null=True, verbose_name='Основной комментарий'),
        ),
        migrations.DeleteModel(
            name='NestedComment',
        ),
    ]
